### ISSUE TITLE
u-blox driver

### ISSUE THREAD

**Issue by jschall** [OpenMotorDrive/framework#15]

**Comment by kd0aij** [comment]
@jschall Has anyone started on this yet? If not, would porting the driver from AP_HAL_GPS be the best way to do it?

**Comment by jschall** [comment]
I think we would need to think about licenaing implications, largely because we may at some point wish to bundle the ublox firmware, and while I don't think there is any licensing issue with doing that, I think that some flexibility in the licensing may help accomplish that politically.

**Comment by kd0aij** [comment]
Are you thinking it would be better to port from PX4? Since it uses pub/sub that might be easier anyway.
